### ISSUE TITLE
感谢校友辛苦之作，但，真的不考虑重构吗？

### ISSUE THREAD

**Issue by wangwanjie** [isnine/HutHelper-Open#1]
简单看了下，代码不规范，结构混乱，作者有考虑用Swift重写吗？

**Comment by isnine** [comment]
重构是肯定的，事实上除了新加功能每天都在改结构。暂时不打算用Swift重写，OC才学了几个月，扎实了再看

**Comment by wangwanjie** [comment]
OC才学几个月。。

**Comment by wangwanjie** [comment]
我记得我还在学校里的时候不是就写了吗？2014年

**Comment by isnine** [comment]
那是Android端和Web端吧，我是16年10月份参与到工大助手里，并开始学OC进行iOS端的开发

**Comment by jackioser** [comment]
cell 的加载不要用nib 加载方法，cell有重用机制:dequeueReusableCellWithIdentifier ,很多地方可以用到UICollectionView 这个，可以看一下

**Comment by isnine** [comment]
感谢提醒，我已经开始重构的工作了。
如果方便的话，可以看下我工程中的校园说说模块(Controllers/Moments和Views/Moments)，还有什么影响性能的地方么。[校园说说模块优化思路](http://www.wxz.name/2017/03/10/hutHelperTableView/)
其他地方的tableview我也将逐渐重构完，再次感谢
