### ISSUE TITLE
图书馆页面建议 返回的时候加个关闭按钮

### ISSUE THREAD

**Issue by zhoupIT** [isnine/HutHelper-Open#2]

**Comment by isnine** [comment]
你好，在图书馆页面，直接左滑不就关闭了么

**Comment by zhoupIT** [comment]
噢噢,发现了,是的呢.

**Comment by zhoupIT** [comment]
兄弟这个不错.我以前一直想给学校做这个.就是不知道咋查成绩和课程表,还有什么选课

**Comment by zhoupIT** [comment]
这个有测试账号吗?...

**Comment by isnine** [comment]
没有测试账号，因为数据都是教务系统的直接过来的。
如果你们学校是正方教务系统的话，可以看看这个仓库，可以直接抓课表https://github.com/isnine/Square，把里面[Config url]改成你学校教务系统的地址
如果不是的话，改一下也行。
喜欢的话，给一个Star

**Comment by zhoupIT** [comment]
好的,看到了.多谢,我试试看

**Comment by isnine** [comment]
嗯 有问题可以再交流
